spring:
  data:
    mongodb:
      host: 114.55.65.144
      port: 27017
      database: note
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 1000MB
fdfs:
  so-timeout: 1500
  connect-timeout: 600
  tracker-list: 114.55.65.144:22122
catalog:
  file-nginx-url: 114.55.65.144:80